### ISSUE TITLE
No data in grafana

### ISSUE THREAD

**Issue by NajibNour** [Festeazy/nginxproxymanagerGraf#3]
Hello Hope you are doing well. I was hoping we can get some further clarification. Ive installed influx db connected it over to grafana and started nginxproxymanagerGraf as you have described. I then imported the dashboard but ive had no luck seeing any data. The nginxproxymanagerGraf container shows the following `lets go and send connection info to influx
43
X.X.X.119
` 
Not sure what else to look for. Influx connections are fine both from grafana and from the nginxproxymanagerGraf container. any guidance would be appreciated!

**Comment by Festeazy** [comment]
Use this fork. This was a very amateur code, someone made it better

https://github.com/ma-karai/nginxproxymanagerGraf

**Comment by NajibNour** [comment]
Hey thanks for the reply! Ive given it a shot and the same issue presents it self.

**Comment by NajibNour** [comment]
Hey hey I revisited this today. Figured out that you need to build the container with the proper influx db parameters within the dockerbuild file. Ive got it to show ips now the issue that i am having now is that it does not pull the domain that the client connected to. Any tips?

**Comment by NajibNour** [comment]
Figured it out The python script was not looking for .ca domains
